export type KatalogAplikasiDataType = {
  nama: string,
  uraian: string,
  fungsi: string,
  layanan: string,
  data: string,
  proses_bisnis: string,
  inputan_data: string,
  supplier_data: string,
  luaran_data: string,
  customer_data: string,
  basis_aplikasi: string,
  tipe_lisensi: string,
  bahasa_pemrograman: string,
  kerangka_pengembangan: string,
  basis_data: string,
  unit_operasional: string,
  unit_pengembang: string,
  raa_level_1: string,
  raa_level_2: string
}